index:
  path: /
  controller: App\Controller\IndexController::index
  methods: GET|HEAD

cart:
  path: /panier
  controller: App\Controller\CartController:show
  methods: GET|HEAD

add-to-cart:
  path: /panier/ajout
  controller: App\Controller\CartController:add

remove-from-cart:
  path: /panier/retirer
  controller: App\Controller\CartController:remove

account:
  path: /mon-compte
  controller: App\Controller\AccountController:show
